### ISSUE TITLE
DMS-Build core layouts

### ISSUE THREAD

**Issue by sangtv-mor** [mor-academy/device-management-system#25]
![Image](https://user-images.githubusercontent.com/130023704/230867513-b3a381cf-6087-4911-ad65-69583d16e2ca.png)

![Image](https://user-images.githubusercontent.com/130023704/230867717-004aea17-49b1-4e1e-a2e7-57a72e0bba06.png)

**Comment by luongluong2000** [comment]
thay thế logo là gì nếu có nhiều công ty trong 1 hệ thống?

**Comment by sangtv-mor** [comment]
Logo này là logo hệ thống DMS không phải là logo cty
